id: P005435
initial_creation_type: ocr
source_metadata:
  id: bdr:W1CZ1479
  title: འཇམ་དབྱངས་ཆོས་རྗེ་རིན་ཆེན་རྒྱལ་མཚན་པའི་གསུང་སྒྲོས་ཁ་ཡར།
  author: ''
  volumes:
    56e0d373f65a47ccbc8017e913dae99c:
      image_group_id: I1CZ1486
      title: ''
      volume_number: 1
      total_pages: 22
      base_file: v001.txt
