id: I888ABB79
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T19:13:06+00:00'
last_modified: '2022-06-08T03:04:12.156276+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ1479
  title: འཇམ་དབྱངས་ཆོས་རྗེ་རིན་ཆེན་རྒྱལ་མཚན་པའི་གསུང་སྒྲོས་ཁ་ཡར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    E66C:
      image_group_id: I1CZ1486
      title: ''
      total_pages: 22
      order: 1
      base_file: E66C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
